allowBuilds:
  '@openrouter/sdk': false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@tanstack/ai-event-client@0.6.4'
  - '@tanstack/ai-openai@0.15.3'
  - '@tanstack/ai-openrouter@0.14.1'
  - '@tanstack/ai@0.33.0'
  - '@tanstack/openai-base@0.8.8'
